export const cars = [
    {
      id: 1,
      brend: 'Remo Hobby',
      title: 'Remo Hobby S Max 1635',
      class: 'Monster Truck',
      scale: '1/16',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '300/200/150 mm',
      motor: '2440 бесколекторний',
      price: '3900 грн',
      driveWheels: 'повний 4WD',
      img: './img/monster/smax.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 2,
      brend: 'Remo Hobby',
      title: 'Remo Hobby M Max 1031',
      class: 'Monster Truck',
      scale: '1/10',
      accumulator: 'Lipo 2s 7.4v 3300 mAh',
      size: '300/200/150 mm',
      motor: '550 колекторний',
      price: '4300 грн',
      driveWheels: 'повний 4WD',
      img: './img/monster/mmax.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 3,
      brend: 'ZD Racing',
      title: 'ZD Racing Pirates 3',
      class: 'Monster Truck',
      scale: '1/8',
      accumulator: 'Lipo 3s 11.1v 5000 mAh',
      size: '300/200/150 mm',
      motor: '2100 бесколекторний',
      price: '12500 грн',
      driveWheels: 'повний 4WD',
      img: './img/monster/pirates3.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 4,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Rocket',
      class: 'Short Course',
      scale: '1/16',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '210/125/285 mm',
      motor: '390 колекторний',
      price: '3100 грн',
      driveWheels: 'повний 4WD',
      img: './img/short/rocket.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 5,
      brend: 'Remo Hobby',
      title: 'Remo Hobby EX3',
      class: 'Short Course',
      scale: '1/10',
      accumulator: 'Lipo 2s 7.4v 3300 mAh',
      size: '300/200/150 mm',
      motor: '550 колекторний',
      price: '4300 грн',
      driveWheels: 'повний 4WD',
      img: './img/short/ex3.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 6,
      brend: 'Remo Hobby',
      title: 'Remo Hobby 9emu',
      class: 'Short Course',
      scale: '1/8',
      accumulator: 'Lipo 2s 7.4v 4200 mAh',
      size: '300/200/150 mm',
      motor: '3650 бесколекторний',
      price: '9500 грн',
      driveWheels: 'повний 4WD',
      img: './img/short/9emu.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 7,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Dingo',
      class: 'Buggy',
      scale: '1/16',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '210/125/285 mm',
      motor: '390 колекторний',
      price: '3100 грн',
      driveWheels: 'повний 4WD',
      img: './img/buggy/dingo.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 8,
      brend: 'ZD Racing',
      title: 'ZD Racing DBX 10',
      class: 'Buggy',
      scale: '1/10',
      accumulator: 'Lipo 3s 7.4v 3300 mAh',
      size: '300/200/150 mm',
      motor: '3650 колекторний',
      price: '4300 грн',
      driveWheels: 'повний 4WD',
      img: './img/buggy/dbx10.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 9,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Scorpion',
      class: 'Buggy',
      scale: '1/8',
      accumulator: 'Lipo 2s 7.4v 4200 mAh',
      size: '300/200/150 mm',
      motor: '3650 бесколекторний',
      price: '9500 грн',
      driveWheels: 'повний 4WD',
      img: './img/buggy/scorpion.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 10,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Crawler 1093',
      class: 'Trophy',
      scale: '1/10',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '210/125/285 mm',
      motor: '390 колекторний',
      price: '3100 грн',
      driveWheels: 'повний 4WD',
      img: './img/trophy/1093.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 11,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Crawler 1073',
      class: 'Trophy',
      scale: '1/10',
      accumulator: 'Lipo 2s 7.4v 4200 mAh',
      size: '300/200/150 mm',
      motor: '3650 бесколекторний',
      price: '9500 грн',
      driveWheels: 'повний 4WD',
      img: './img/trophy/1073.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 12,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Sevor',
      class: 'Truggy',
      scale: '1/16',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '210/125/285 mm',
      motor: '390 колекторний',
      price: '3100 грн',
      driveWheels: 'повний 4WD',
      img: './img/truggy/sevor.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 13,
      brend: 'ZD Racing',
      title: 'ZD Racing Pirates 3',
      class: 'Truggy',
      scale: '1/8',
      accumulator: 'Lipo 3s 7.4v 3300 mAh',
      size: '300/200/150 mm',
      motor: '3650 колекторний',
      price: '4300 грн',
      driveWheels: 'повний 4WD',
      img: './img/truggy/pirates.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 14,
      brend: 'Remo Hobby',
      title: 'Remo Hobby Evo-R',
      class: 'Truggy',
      scale: '1/8',
      accumulator: 'Lipo 2s 7.4v 4200 mAh',
      size: '300/200/150 mm',
      motor: '3650 бесколекторний',
      price: '9500 грн',
      driveWheels: 'повний 4WD',
      img: './img/truggy/evo-r.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 15,
      brend: 'WPL',
      title: 'WPL B-36',
      class: 'Crawler',
      scale: '1/16',
      accumulator: 'Li-Ion 7.4v 1500 mAh',
      size: '210/125/285 mm',
      motor: '390 колекторний',
      price: '3100 грн',
      driveWheels: 'повний 4WD',
      img: './img/crawler/b36.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 16,
      brend: 'WPL',
      title: 'WPL C-34',
      class: 'Crawler',
      scale: '1/10',
      accumulator: 'Lipo 3s 7.4v 3300 mAh',
      size: '300/200/150 mm',
      motor: '3650 колекторний',
      price: '4300 грн',
      driveWheels: 'повний 4WD',
      img: './img/crawler/c34.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    },
    {
      id: 17,
      brend: 'WPL',
      title: 'WPL B-24',
      class: 'Crawler',
      scale: '1/16',
      accumulator: 'Lipo 2s 7.4v 4200 mAh',
      size: '300/200/150 mm',
      motor: '3650 бесколекторний',
      price: '9500 грн',
      driveWheels: 'повний 4WD',
      img: './img/crawler/b24.jpg',
      maxSpeed: 'до 42 км/год',
      width: '210 мм',
      height: '125 мм',
      length: '285 мм',
      timeWork: '20 хвилин',
      signal: 'до 100 метрів',
    }
  ];